-- MySQL Script generated by MySQL Workbench
-- Fri 27 Feb 2015 08:23:27 PM EST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema LiquiZ
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LiquiZ` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema TUTORIALS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TUTORIALS` DEFAULT CHARACTER SET latin1 ;
USE `LiquiZ` ;

-- -----------------------------------------------------
-- Table `LiquiZ`.`Policies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`Policies` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`Policies` (
  `PolID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Attempts` INT NOT NULL DEFAULT 1,
  `Timed` BIT(1) NOT NULL DEFAULT 0,
  `TimeLimit` INT NULL DEFAULT NULL,
  `ShowAns` BIT(1) NOT NULL DEFAULT 0,
  `Scored` BIT(1) NOT NULL DEFAULT 1,
  `Grade` INT NOT NULL,
  `ShuffleQues` BIT(1) NOT NULL DEFAULT 0,
  `ShuffleAns` BIT(1) NOT NULL DEFAULT 0,
  `AccessCode` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`PolID`),
  UNIQUE INDEX `PolID_UNIQUE` (`PolID` ASC));


-- -----------------------------------------------------
-- Table `LiquiZ`.`DisplayElements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`DisplayElements` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`DisplayElements` (
  `DispElID` INT NOT NULL AUTO_INCREMENT,
  `Type` CHAR(4) NOT NULL,
  `TextElement` VARCHAR(32768) NULL COMMENT 'pure text content',
  `MediaElement` VARCHAR(32768) NULL COMMENT 'video, picture or sounds, store the path of file',
  PRIMARY KEY (`DispElID`));


-- -----------------------------------------------------
-- Table `LiquiZ`.`Quizzes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`Quizzes` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`Quizzes` (
  `QuizID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `Desc` INT NULL DEFAULT NULL,
  `Policy` INT NOT NULL,
  `Privacy` CHAR(1) NOT NULL,
  PRIMARY KEY (`QuizID`),
  UNIQUE INDEX `QID_UNIQUE` (`QuizID` ASC));


-- -----------------------------------------------------
-- Table `LiquiZ`.`Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`Questions` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`Questions` (
  `QuesID` INT NOT NULL AUTO_INCREMENT,
  `Points` INT NOT NULL,
  `Level` INT NULL DEFAULT NULL,
  `QType` CHAR(4) NOT NULL,
  PRIMARY KEY (`QuesID`),
  UNIQUE INDEX `QuesID_UNIQUE` (`QuesID` ASC))
COMMENT = 'QuesID and some attributes of it. ';


-- -----------------------------------------------------
-- Table `LiquiZ`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`Courses` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`Courses` (
  `CourseID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(32768) NOT NULL,
  `Privacy` CHAR(1) NOT NULL,
  PRIMARY KEY (`CourseID`),
  UNIQUE INDEX `CID_UNIQUE` (`CourseID` ASC));


-- -----------------------------------------------------
-- Table `LiquiZ`.`CoursesQuizzes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`CoursesQuizzes` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`CoursesQuizzes` (
  `CourseID` INT NULL DEFAULT NULL,
  `QuizID` INT NULL DEFAULT NULL,
  `Sequence` INT NULL DEFAULT NULL);


-- -----------------------------------------------------
-- Table `LiquiZ`.`Quizzes_QuesCons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`Quizzes_QuesCons` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`Quizzes_QuesCons` (
  `QuizID` INT NOT NULL,
  `QuesConID` INT NOT NULL,
  `QuesSequence` INT NULL)
COMMENT = 'multi to multi ' /* comment truncated */ /*QuizID vs QuesConID*/;


-- -----------------------------------------------------
-- Table `LiquiZ`.`QuesCon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`QuesCon` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`QuesCon` (
  `QuesConID` INT NOT NULL AUTO_INCREMENT,
  `Element` INT NULL DEFAULT NULL,
  `Type` CHAR(4) NOT NULL,
  PRIMARY KEY (`QuesConID`),
  UNIQUE INDEX `QuesConID_UNIQUE` (`QuesConID` ASC))
COMMENT = 'A problem and its choices or fill boxes included in a QuesCon. ';


-- -----------------------------------------------------
-- Table `LiquiZ`.`Answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`Answers` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`Answers` (
  `AnsID` INT NOT NULL AUTO_INCREMENT,
  `Response` INT NULL DEFAULT NULL,
  `Element` INT NULL DEFAULT NULL COMMENT 'The DispEl that represents the answer',
  `LowBound` INT NULL DEFAULT NULL COMMENT 'to accept a range of numbers (lower bound)',
  `HighBound` INT NULL DEFAULT NULL COMMENT 'to accept a range of numbers (upper bound)',
  PRIMARY KEY (`AnsID`));


-- -----------------------------------------------------
-- Table `LiquiZ`.`StdSet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`StdSet` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`StdSet` (
  `StdSetID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`StdSetID`));


-- -----------------------------------------------------
-- Table `LiquiZ`.`StdChoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`StdChoices` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`StdChoices` (
  `StdSetID` INT NOT NULL,
  `Element` INT NOT NULL,
  `Sequence` INT NOT NULL);


-- -----------------------------------------------------
-- Table `LiquiZ`.`QuesAnsSeq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`QuesAnsSeq` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`QuesAnsSeq` (
  `QuesID` INT NOT NULL,
  `Ans` INT NULL DEFAULT NULL,
  `StdSetID` INT NULL DEFAULT NULL,
  `StdChoice` INT NULL DEFAULT NULL,
  `Sequence` INT NULL DEFAULT NULL,
  `Correct` BIT(1) NULL DEFAULT NULL);


-- -----------------------------------------------------
-- Table `LiquiZ`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`Users` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`Users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(255) NOT NULL,
  `LastName` VARCHAR(255) NOT NULL,
  `Username` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UserID`));


-- -----------------------------------------------------
-- Table `LiquiZ`.`UserPermissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`UserPermissions` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`UserPermissions` (
  `UserID` INT NOT NULL,
  `Entity` INT NULL DEFAULT NULL COMMENT 'Course or Quiz... other Users?',
  `EType` CHAR(4) NULL DEFAULT NULL COMMENT 'Course or Quiz... other Users?',
  `Permissions` INT NULL DEFAULT NULL COMMENT 'each bit represents a permission');


-- -----------------------------------------------------
-- Table `LiquiZ`.`StudentResponses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`StudentResponses` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`StudentResponses` (
  `Student` INT NOT NULL,
  `Ques` INT NOT NULL,
  `Response` INT NOT NULL,
  `Correct` BIT(1) NULL DEFAULT NULL);


-- -----------------------------------------------------
-- Table `LiquiZ`.`StudentQuizScores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`StudentQuizScores` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`StudentQuizScores` (
  `Student` INT NOT NULL,
  `Quiz` INT NOT NULL,
  `Score` INT NOT NULL);


-- -----------------------------------------------------
-- Table `LiquiZ`.`StudentGrades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`StudentGrades` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`StudentGrades` (
  `Student` INT NOT NULL,
  `Course` INT NOT NULL,
  `Grade` DOUBLE NOT NULL);


-- -----------------------------------------------------
-- Table `LiquiZ`.`QuesCons_DisplayElements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`QuesCons_DisplayElements` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`QuesCons_DisplayElements` (
  `QuesConID` INT NOT NULL,
  `DispElID` INT NOT NULL,
  `DispElSequence` INT NULL)
ENGINE = InnoDB
COMMENT = 'multi to multi, Question Container ~ DIsplay Elements';


-- -----------------------------------------------------
-- Table `LiquiZ`.`QuesCon_Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`QuesCon_Questions` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`QuesCon_Questions` (
  `QuesConID` INT NOT NULL,
  `QuesID` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LiquiZ`.`Questions_DIsplayElements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LiquiZ`.`Questions_DIsplayElements` ;

CREATE TABLE IF NOT EXISTS `LiquiZ`.`Questions_DIsplayElements` (
  `QuesID` INT NOT NULL,
  `DispElID` INT NOT NULL,
  `DispElSequence` INT NULL)
ENGINE = InnoDB
COMMENT = 'multi to multi' /* comment truncated */ /*Questions ~ Display Elements*/;

USE `TUTORIALS` ;

-- -----------------------------------------------------
-- Table `TUTORIALS`.`tcount_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TUTORIALS`.`tcount_tbl` ;

CREATE TABLE IF NOT EXISTS `TUTORIALS`.`tcount_tbl` (
  `tutorial_author` VARCHAR(40) NULL DEFAULT NULL,
  `tutorial_count` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TUTORIALS`.`testalter_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TUTORIALS`.`testalter_tbl` ;

CREATE TABLE IF NOT EXISTS `TUTORIALS`.`testalter_tbl` (
  `c` CHAR(10) NULL DEFAULT NULL,
  `i` INT(11) NULL DEFAULT '1000')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TUTORIALS`.`tutorials_tbl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TUTORIALS`.`tutorials_tbl` ;

CREATE TABLE IF NOT EXISTS `TUTORIALS`.`tutorials_tbl` (
  `tutorial_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tutorial_title` VARCHAR(100) NOT NULL,
  `tutorial_author` VARCHAR(40) NOT NULL,
  `submission_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`tutorial_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;

USE `LiquiZ` ;

-- -----------------------------------------------------
-- Placeholder table for view `LiquiZ`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LiquiZ`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `LiquiZ`.`view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `LiquiZ`.`view1` ;
DROP TABLE IF EXISTS `LiquiZ`.`view1`;
USE `LiquiZ`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
