package org.adastraeducation.liquiz.test;


import java.util.ArrayList;
import java.util.Arrays;

import org.adastraeducation.liquiz.*;
public class TestQuizJavascript {
	public static void main(String[] a) {
		int qid=0;
		int qcid=0;
		Policy p = new Policy();
		Quiz quiz = new Quiz(1, "Java1", "Java Quiz 1", p);
		
		QuestionContainer qc = 
				new QuestionContainer(qcid++, "Operators", "fillin", new ArrayList<Displayable>());
		qc.add(new QuestionText("What is 2+2?"));
		qc.add(new Image("dinosaur.jpg", 100, 100));
		ArrayList<Answer> answers = new ArrayList<Answer>();
		answers.add(new Answer(new AnswerText("4"), true));
		qc.add(new FillIn(qid++, 1, 1, answers));
		quiz.addQuestion(qc);
		
		
		//test for question 1 in QuizDemo_ajax.jsp, not good, line 12: 0 not printed, line 14: "1_1" not printed and numbers printed as doubles, not ints, line 15: entire line not printed,
		qc=new QuestionContainer(qcid++,"Mergesort","grid",new ArrayList<Displayable>());
		qc.add(new InstructionText("Show the first pass of Mergesort below"));
		Matrix m=new Matrix(1,9);
		m.setData(new double[][]{new double[]{9,8,7,6,5,4,3,2,1}});
		qc.add(m);
		qc.add(new MatrixQuestion(qid++,10,100,1,9));
		quiz.addQuestion(qc);
		
		
		//test for question 2 in QuizDemo_ajax.jsp, not good, line 23 and 25 completely not printed
		qc=new QuestionContainer(qcid++,"Matrix Multiplication","matrix",new ArrayList<Displayable>());
		qc.add(new InstructionText("Show the result of matrix A * B"));
		Matrix m1=new Matrix(3,3);
		m1.setData(new double[][]{{1,0,2},{1,1,-2},{2,1,0}});
		qc.add(m1);
		Matrix m2=new Matrix(3,3);
		m2.setData(new double[][]{{1,1,-1},{-2,1,0},{1,1,3}});
		qc.add(m2);
		qc.add(new MatrixQuestion(qid++,10,100,3,3));
		quiz.addQuestion(qc);
		
		
		// test for question 3 in QuizDemo_ajax.jsp, good
		qc=new QuestionContainer(qcid++,"Java","code",new ArrayList<Displayable>());     
		qc.add(new InstructionText("Complete the code below so that it prints 'hello'"));
		qc.add(new Code(qid++,10,80,"public A {\n  void   (String[] args) {\n  System.\n  }\n}\n"));
		quiz.addQuestion(qc);
		
		
		//test for question 4 in QuizDemo_ajax.jsp, good
		qc=new QuestionContainer(qcid++,"Java","code", new ArrayList<Displayable>());
		qc.add(new InstructionText("Complete the following function so it computes factorial recursively."));
		qc.add(new Code(qid++,10,80,"public static void fact(int n) {\n\n\n\n}"));
		quiz.addQuestion(qc);
		
		
		//test for question 5 in QuizDemo_ajax.jsp,
		//not sure how to set up this test
		qcid++;
		qid++;
		
		
		//test for question 6 in QuizDemo_ajax.jsp,
		//not sure how to set up this test
		qcid++;
		qid++;
		
		
		//test for question 7 in QuizDemo_ajax.jsp, good
		qc=new QuestionContainer(qcid++,"File Upload","file",new ArrayList<Displayable>());       
		qc.add(new InstructionText("Submit your homework for the 3n+1 problem as a single .java file"));
		qc.add(new FileUpload(qid++,10,100,".java"));
		quiz.addQuestion(qc);
		
		
		//test for question 8 in QuizDemo_ajax.jsp, not good: missing lines 70 in the QuizDemo_ajax.jsp file, also how to give matrix info about its header on java side?
		qc=new QuestionContainer(qcid++,"Graph Theory","matrix",new ArrayList<Displayable>());      
		qc.add(new InstructionText("Find the shortest path from vertex 1 to 5.  Leave any cost blank if the vertex is unreachable."));
		qc.add(new Image("Bellmanford_3.png",4,4));
		qc.add(new MatrixQuestion(qid++,10,100,6,6));
		quiz.addQuestion(qc);
		
		
		//no question 9
		qcid++;
		qid++;
		
		
		//test for question 10 in QuizDemo_ajax.jsp, not good: line 78 in the QuizDemo_ajax.jsp file uses Util.span, but the code generated by this java file uses page.instructions
		qc=new QuestionContainer(qcid++,"Arithmetic","fillin",new ArrayList<Displayable>());      
		qc.add(new QuestionText("What is 2+2"));
		qc.add(new FillIn(qid++,10,100));
		quiz.addQuestion(qc);
		
		
		//test for question 11 in QuizDemo_ajax.jsp, commented out because the writeJS function is not written and caused an error
		qc=new QuestionContainer(qcid++,"Dinosaur","mcRadioImg",new ArrayList<Displayable>());
		qc.add(new QuestionText("Which one is the dinosaur?"));
		qc.add(new MultiChoiceRadio(qid++,10,100,new ArrayList<Answer>(Arrays.asList(new Answer(),new Answer(),new Answer()))));
		//quiz.addQuestion(qc);
		
		
		//test for question 12 in QuizDemo_ajax.jsp,
		//not sure how to set up the test for this one
		qcid++;
		qid++;
		
		
		//test for question 13 in QuizDemo_ajax.jsp, not good line 104: doesn't exist because I don't know which class file to use
		qc=new QuestionContainer(qcid++,"Multimedia","audio", new ArrayList<Displayable>());
		qc.add(new InstructionText("listen to the following audio file and pick the name of the main character."));
		qc.add(new Audio("clip1.mp3"));
		qid++;
		quiz.addQuestion(qc);
		
		
		//test for question 14 in QuizDemo_ajax.jsp, not good, line 111: doesn't exist
		qc=new QuestionContainer(qcid++,"Tacoma Narrows", "video", new ArrayList<Displayable>());
		qc.add(new InstructionText("Watch the following video, then explain what caused the bridge to fail."));
		qc.add(new Video("Tacoma Narrows Bridge Collapse.mp4",10,10));
		qc.add(new Essay(qcid++,10,100,""));
		quiz.addQuestion(qc);
		
		
		//test for question 15 in QuizDemo_ajax.jsp, not good, line 117: page.numeric not generated, page.fillin generated instead
		qc=new QuestionContainer(qcid++,"Arithmetic", "numeric", new ArrayList<Displayable>());
		qc.add(new QuestionText("What is the square root of 2 (four digits is fine)?"));
		qc.add(new FillIn(qid++,100,10,new Answer()));
		quiz.addQuestion(qc);
		
		
		//test for question 16 in QuizDemo_ajax.jsp
		//not sure how to set up the test for this one
		qcid++;
		qid++;
		
		
		//test for question 17 in QuizDemo_ajax.jsp
		//not sure how to set up the test for this one
		
		
		
		
		DisplayContext dc = new DisplayContext();
		quiz.writeJS(dc);
		System.out.println(dc.toString());
		
	}
	
}
