package org.adastraeducation.liquiz.test;


import java.util.ArrayList;

import org.adastraeducation.liquiz.*;
public class TestQuizJavascript {
	public static void main(String[] a) {
		int qid=2;
		int qcid=2;
		Policy p = new Policy();
		Quiz quiz = new Quiz(1, "Java1", "Java Quiz 1", p);
		
		QuestionContainer qc = 
				new QuestionContainer(qcid++, "Operators", "fillin", new ArrayList<Displayable>());
		qc.add(new Text("What is 2+2?"));
		qc.add(new Image("dinosaur.jpg", 100, 100));
		ArrayList<Answer> answers = new ArrayList<Answer>();
		answers.add(new Answer(new Text("4"), true));
		qc.add(new FillIn(qid++, 1, 1, answers));
		quiz.addQuestion(qc);
		
		
		// test for question 3 in QuizDemo_ajax.jsp, seems to work as far as I (Ethan Murad) can tell
		qc=new QuestionContainer(qcid++,"Java","code",new ArrayList<Displayable>());     
		qc.add(new Text("Complete the code below so that it prints 'hello'"));
		qc.add(new Code(qid++,10,80,"public A {\n  void   (String[] args) {\n  System.\n  }\n}\n"));
		quiz.addQuestion(qc);
		
		
		//test for question 4 in QuizDemo_zjax.jsp
		qc=new QuestionContainer(qcid++,"Java","code", new ArrayList<Displayable>());
		qc.add(new Text("Complete the following function so it computes factorial recursively."));
		qc.add(new Code(qid++,10,80,"public static void fact(int n) {\n\n\n\n}"));
		quiz.addQuestion(qc);
		
		
		qcid++;
		qcid++;
		qid++;
		qid++;
		
		
		//test for question 7 in QuizDemo_ajax.jsp seems to work as far as I (Ethan Murad) can tell
		qc=new QuestionContainer(qcid++,"File Upload","file",new ArrayList<Displayable>());       
		qc.add(new Text("Submit your homework for the 3n+1 problem as a single .java file"));
		qc.add(new FileUpload(qid++,10,100,".java"));
		quiz.addQuestion(qc);
		
		
		//test for question 8 in QuizDemo_ajax.jsp, missing lines 70 in the QuizDemo_ajax.jsp file, I (Ethan Murad) wasn't sure which function should generate those lines.  writeJS function, but which class file?
		qc=new QuestionContainer(qcid++,"Graph Theory","matrix",new ArrayList<Displayable>());      
		qc.add(new Text("Find the shortest path from vertex 1 to 5.  Leave any cost blank if the vertex is unreachable."));
		qc.add(new Image("Bellmanford_3.png",4,4));
		qc.add(new MatrixQuestion(qid++,10,100,6,6));
		quiz.addQuestion(qc);
		
		
		qcid++;
		qid++;
		
		
		//test for question 10 in QuizDemo_ajax.jsp, seems to work as far as I (Ethan Murad) can tell, except for line 78 in the QuizDemo_ajax.jsp file, because that file uses Util.span, but the code generated by this java file uses page.instructions
		qc=new QuestionContainer(qcid++,"Arithmetic","fillin",new ArrayList<Displayable>());      
		qc.add(new Text("What is 2+2"));
		qc.add(new FillIn(qid++,10,100));
		quiz.addQuestion(qc);
		
		
		DisplayContext dc = new DisplayContext();
		quiz.writeJS(dc);
		System.out.println(dc.toString());
		
	}
	
}
